SELECT PLT_CN, METADATA_CN, QUEST_NAME, RESPONSE_VALUE
  FROM FS_NWOS.PLOT_OWNER PO,
       FS_NWOS.OWNER      O,
       FS_NWOS.SAMPLE     S,
       FS_NWOS.RESPONSE   R,
       FS_NWOS.QUEST      Q
 WHERE PO.OWNER_CN = O.CN
   AND S.OWNER_CN = O.CN
   AND R.SAMPLE_CN = S.CN
   AND Q.RESPONSE_CN = R.CN
   AND S.NWOS_STUDY = 'base'
   /*ADD STUDY YEAR*/
   AND PO.ORIGIN = 'P2'
   AND O.OWNCD_NWOS = 45
   AND R.RESPONSE_CD = 1
   AND Q.RESPONSE_VALUE <> -1
   AND Q.METADATA_CN in ('QMD59', 'QMD63', 'QMD84', 'QMD85')
 GROUP BY PLT_CN, METADATA_CN, QUEST_NAME, RESPONSE_VALUE
