SELECT PLT_CN, S.NWOSYR
  FROM FS_NWOS.PLOT_OWNER PO,
       FS_NWOS.OWNER      O,
       FS_NWOS.SAMPLE     S,
       FS_NWOS.RESPONSE   R
 WHERE PO.OWNER_CN = O.CN
   AND S.OWNER_CN = O.CN
   AND R.SAMPLE_CN = S.CN
   AND S.NWOS_STUDY = 'base'
   AND S.NWOS_CYCLE = '2018'
   AND PO.ORIGIN = 'P2'
   AND O.OWNCD_NWOS = 45
   AND R.RESPONSE_CD = 1
 ORDER BY PLT_CN
